SUPABASE_URL="https://zdohcbyruaxidrxnmewe.supabase.co"
SUPABASE_ANON_KEY="sb_publishable__jf83ld5w3N3qCm-ZFODsw_GHQKamyl"
APP_PEPPER="Xg83ks92Kdj38Ks93kD82kdK39dkD83k"
ORGANIZER_MASTER_KEY="TB_MASTER_9sd8Kds82Kdj38dK"